return {
  require 'plugins.treesitter',
  require 'plugins.telescope',
  require 'plugins.cmp',
  require 'plugins.lsp',
  require 'plugins.others',

  require 'plugins.theme',
  require 'plugins.indent_blankline',
  require 'plugins.harpoon',
  require 'plugins.copilot',
  require 'plugins.copilot_chat',
  require 'plugins.database',
  require 'plugins.comment',
  require 'plugins.conform',
  require 'plugins.term',
  require 'plugins.gitsigns',
  require 'plugins.autopairs',
  require 'plugins.trouble',
  require 'plugins.todo',
  require 'plugins.lualine',
  require 'plugins.mini',
  require 'plugins.debug',
  require 'plugins.tests',
  require 'plugins.nvim_tree',
  require 'plugins.lint',
}
